###
 # THIS FILE IS AUTOMATICALLY GENERATED
 # Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: 19c33ffcc3ca67d5
# Executable: ./bin/champsim
# Module Names: ('btbDbasic_btb', 'branchDbimodal', 'branchDgshare', 'branchDhashed_perceptron', 'branchDperceptron', 'prefetcherDip_stride', 'prefetcherDnext_line', 'prefetcherDno', 'prefetcherDspp_dev', 'prefetcherDva_ampm_lite', 'replacementDdrrip', 'replacementDhawkeye', 'replacementDlru', 'replacementDrandom', 'replacementDship', 'replacementDsrrip')
######

BIN_ROOT := bin
compile_commands $(BIN_ROOT)/champsim: build_id := \
  19c33ffcc3ca67d5
nonbase_module_objs += $(filter-out $(base_module_objs),$(call get_module_list, btb/basic_btb \
  branch/bimodal branch/gshare branch/hashed_perceptron \
  branch/perceptron prefetcher/ip_stride prefetcher/next_line \
  prefetcher/no prefetcher/spp_dev prefetcher/va_ampm_lite \
  replacement/drrip replacement/hawkeye replacement/lru \
  replacement/random replacement/ship replacement/srrip \
  ))
build_ids += 19c33ffcc3ca67d5
executable_name += $(BIN_ROOT)/champsim
